[INPUT]
INPUT_DIR=../../data/med_reviews_corpora/merged_reviews

[PARAMETERS]
# 0 2 3 5 13 17 21 42 67 123
SEED=42
MAX_SEQ_LENGTH=128
BATCH_SIZE=64
LEARNING_RATE=3e-5
DROPOUT=0.3
NUM_EPOCHS=10
MODEL_NAME=cimm-kzn/enrudr-bert

[OUTPUT]
CHKPT_NAME=ruen_ckpt
OUTPUT_DIR=checkpoints/
EVALUATION_FILENAME=evaluation.txt

