[INPUT]
INPUT_DIR=../training/smm4h_2021/posteval_stage/ru/bi_attention/simple_first
#../training/smm4h_2021/validation_stage/en/mono_attention_pretrained/simple
#training/smm4h_2021/validation_stage/ru/bi_attention_pretrained/simple
#../training/smm4h_2021/validation_stage/ru/mono_sider/simple
#../training/smm4h_2021/validation_stage/ru/bi_sider/weighted_loss
#../training/smm4h_2021/validation_stage/ru/bi_nodrug/weighted_loss
#../training/smm4h_2021/validation_stage/en/roberta/mono_drug/weighted_loss
#../training/smm4h_2021/validation_stage/en/roberta/mono_nodrug/weighted_loss
#../training/smm4h_2021/validation_stage/ru/mono_nodrug/simple
#../training/smm4h_2021/validation_stage/ruen/bilingual_drug/weighted_loss
#../training/smm4h_2021/validation_stage/en/monolingual_drug/weighted_loss
DATA_PATH=../../data/smm4h_21_data/post_eval/ru/test.tsv


[OUTPUT]
OUTPUT_PATH=avg_qualitity/smm4h_2021/ru/posteval_stage/simple_bi_attention_first.csv
#avg_qualitity/transformers17/weighted_loss_gelu_drop/ruen_nodrug.csv