[INPUT]
# mono bi
TRAIN_TYPE=mono
INPUT_DIR=../../data/smm4h_21_data/ru/tweets_w_smiles_val_stage
#../../data/smm4h_21_data/ruen/tweets_w_smiles_val_stage
#../../data/smm4h_21_data/en/tweets_w_smiles_val_stage
#../../data/smm4h_21_data/ru/tweets_w_smiles_val_stage
#../../data/ru_tweets_w_smiles
#../../data/tweets_w_drug_embeddings/
BILINGUAL_INPUT_DIR=../../data/smm4h_21_data/ru/tweets_w_smiles_val_stage
#../../data/ruen_tweets_w_smiles
#../../data/tweets_w_drug_embeddings/
# chemberta file
DRUG_EMBEDDINGS_FROM=sider
[PARAMETERS]
# 0 2 3 5 13 17 21 42 67 123
SEED=0
MAX_TEXT_LENGTH=128
MAX_MOLECULE_LENGTH=256
BATCH_SIZE=64
LEARNING_RATE=1e-5
DROPOUT=0.3
NUM_EPOCHS=10
APPLY_UPSAMPLING=no
USE_WEIGHTED_LOSS=no
# nodrug/drug/attention
MODEL_TYPE=drug
TEXT_ENCODER_NAME=cimm-kzn/enrudr-bert
#cimm-kzn/enrudr-bert

[CROSSATT_PARAM]
CROSSATT_DROPOUT=0.1
CROSSATT_HIDDEN_DROPOUT=0.1

[OUTPUT]
OUTPUT_DIR=smm4h_2021/validation_stage/ru/mono_sider/simple/seed_0
EVALUATION_FILENAME=evaluation.txt

[SIDER]
EMBS_PATH_GZ=../../data/sider_embs/embeds_drugbank_sider_v1_db_ids.csv.gz
