[INPUT]
INPUT_DIR = ../../data/ru_tweets_w_smiles
#../../data/tweets_w_drug_embeddings/
BILINGUAL_INPUT_DIR=../../data/ruen_tweets_w_smiles
#../../data/tweets_w_drug_embeddings/
# chemberta file
DRUG_EMBEDDINGS_FROM=chemberta
[PARAMETERS]
# 0 2 3 5 13 17 21 42 67 123
SEED=0
MAX_TEXT_LENGTH=128
MAX_MOLECULE_LENGTH=256
BATCH_SIZE=64
LEARNING_RATE=3e-5
DROPOUT=0.3
NUM_EPOCHS=5
APPLY_UPSAMPLING = no
# ru-nodrug/ru-drug/ruen-nodrug/ruen-drug
MODEL_TYPE=ru_nodrug

[OUTPUT]
OUTPUT_DIR=transformers17/ru_nodrug/no_upsampling_gelu_drop/seed_0
EVALUATION_FILENAME=evaluation.txt

