[INPUT]
INPUT_DIR = ../../data/tweets_w_drug_embeddings/
BILINGUAL_INPUT_DIR=../../data/tweets_w_drug_embeddings/
MODEL_DIR=/home/tlenusik/DATA/pretrained_models/downloading_models/rudr-bert_deep_pavlov/checkpoint-800000
#/home/tlenusik/DATA/pretrained_models/rudr-bert_deep_pavlov_p/checkpoint-3100000
#/home/tlenusik/DATA/pretrained_models/downloading_models/rudr-bert_deep_pavlov/checkpoint-800000/
#/home/tlenusik/DATA/pretrained_models/rudr-bert_deep_pavlov_p/checkpoint-3100000
[PARAMETERS]
SEED=9
MAX_TEXT_LENGTH=128
MAX_MOLECULE_LENGTH=256
BATCH_SIZE=64
LEARNING_RATE=1e-5
NUM_EPOCHS=10
APPLY_UPSAMPLING = no
# ru-nodrug/ru-drug/ruen-nodrug/ruen-drug
MODEL_TYPE=ru_nodrug

[OUTPUT]
OUTPUT_DIR=rudr_deeppavlov_v3/seed_9
EVALUATION_FILENAME=evaluation.txt

